[package]
name = "Contract"
version = "0.0.1"
authors = ["Your Name <your.email@example.com>"]

[addresses]
Contract = "0x48bd1b77a08117f0a89a50314b84c22e1991d7feac0f1e8de90cede8b43ee151"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"