[package]
name = "Contract"
version = "0.0.1"
authors = [""]

[addresses]
Contract = "0x30ed1b735e58ff52853fb862c0cded727f11c277e82aec24082e2ab63fe74c27"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "devnet", subdir = "aptos-move/framework/aptos-framework" }