[package]
name = "Contract"
version = "0.0.1"
authors = ["Move Project Manager"]

[addresses]
Contract = "0xe8d532de3a122759fdf2ed724e8461584bf2b282a55f500fd6473e814da7d264"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"