[package]
name = "staking"
version = "0.1.0"
authors = ["Your Name <youremail@example.com>"]

[addresses]
Std = "0x1"

[dependencies]
# No external dependencies beyond std

[features]
default = []

[[modules]]
name = "Staking"
address = "0x1"
path = "sources/staking.move"