[package]
name = "Contract"
version = "0.1.0"
authors = [""] 

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "mainnet" }

[addresses]
Contract = "0x1"